This homework is intended to help you get to grips with some standard plots, analyses, and cleaning methods you may need to use in your research. It is created as a self learning tool so that you can follow along after taking the Python Beginner or Beginner+ course. 

Topics covered:

    -   Working with different data types: SPSS, SAS, STATA, excel, json, MATLAB

    -   Categorical data in Python
    
    -   Cleaning: filtering data, changing values, deal with NAs, getting values from text, splitting up text
    
    -   Plots: bar, scatter, line, pie, heatmap, map
    
    -   Regressions, basic ML analyses

Requirements:

    -   A couple of additional package installs (included in the notebook, just uncomment the lines to install them)
    
    -   Some reading of documentation
    
    -   Willingness to do additional reading to build up background knowledge
    
    -   A couple of hours

# Opening data

This course has covered working with csv files due to their lightweight and accessibility (many programs and tools can open and work with them). However, many fields work with different data types, in this section we will take a look at a few common proprietary and open source data types and how you can open them into a data type used in the course.

### .sav (SPSS)

To work with the SPSS data file type .sav we will use a package called [pyreadstat](https://github.com/Roche/pyreadstat). It is available as a package on pypi, meaning we can simply [pip install](https://pip.pypa.io/en/stable/cli/pip_install/) it.

In [4]:
# Uncomment the line below to install the needed package
#%pip install pyreadstat

There are two parts to a sav file, the data and the labels. pyreadstat refers to the labels (and additional data) as the metadata, so when opening an SPSS data file there are two variables needed to store it.

In [ ]:
import pyreadstat

df, meta = pyreadstat.read_sav("job_satisfaction.sav")
# Take a look at the data, what format is it?
df

Collecting pandas
  Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tis254\documents\python-software-carpentry\.venv\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tis254\documents\python-software-carpentry\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\tis254\documents\python-software-carpentry\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

,Gender,Age,MStatus,Children#,Education,Ethnicity,Yeas#,Location,MStatus_Rec,Education_Rec,...,Salary,Promotion,Autonomy,RoleConflict,Comfort,WorkLoad,AnyChild,North,Center,South
0,1.0,37.0,1.0,2.0,1.0,0.0,5.0,1.0,0.0,0.0,...,8.0,15.0,18.0,5.0,19.0,15.0,1.0,1.0,0.0,0.0
1,0.0,56.0,1.0,3.0,1.0,0.0,29.0,3.0,0.0,0.0,...,18.0,41.0,12.0,7.0,15.0,14.0,1.0,0.0,0.0,1.0
2,1.0,32.0,1.0,3.0,1.0,1.0,8.0,2.0,0.0,0.0,...,28.0,33.0,9.0,9.0,14.0,9.0,1.0,0.0,1.0,0.0
3,0.0,30.0,1.0,1.0,1.0,1.0,3.0,1.0,0.0,0.0,...,35.0,46.0,15.0,10.0,10.0,13.0,1.0,1.0,0.0,0.0
4,1.0,41.0,1.0,2.0,1.0,0.0,15.0,3.0,0.0,0.0,...,20.0,39.0,15.0,10.0,13.0,13.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,1.0,45.0,1.0,5.0,3.0,0.0,12.0,3.0,0.0,0.0,...,13.0,20.0,21.0,6.0,17.0,16.0,1.0,0.0,0.0,1.0
214,1.0,44.0,1.0,3.0,3.0,1.0,11.0,1.0,0.0,0.0,...,17.0,27.0,14.0,9.0,13.0,12.0,1.0,1.0,0.0,0.0
215,1.0,43.0,1.0,3.0,3.0,0.0,16.0,3.0,0.0,0.0,...,24.0,26.0,14.0,6.0,15.0,13.0,1.0,0.0,0.0,1.0
216,1.0,43.0,1.0,5.0,3.0,0.0,20.0,3.0,0.0,0.0,...,20.0,12.0,9.0,8.0,24.0,6.0,1.0,0.0,0.0,1.0
217,1.0,NaN,3.0,3.0,3.0,0.0,35.0,3.0,1.0,0.0,...,4.0,13.0,6.0,14.0,13.0,16.0,1.0,0.0,0.0,1.0

The name given to the variable probably gave it away, but this packages can open the data from sav file directly into a pandas dataframe. Super useful!

In [ ]:
# What about the metadata?
meta

metadata_container(column_names=['Gender', 'Age', 'MStatus', 'Children#', 'Education', 'Ethnicity', 'Yeas#', 'Location', 'MStatus_Rec', 'Education_Rec', 'Satisfaction', 'Burnout', 'Turnover', 'Colleague', 'Supervision', 'Salary', 'Promotion', 'Autonomy', 'RoleConflict', 'Comfort', 'WorkLoad', 'AnyChild', 'North', 'Center', 'South'], column_labels=[None, None, None, '# of Children', None, None, '# of Years at Current Job', 'Region', 'Marital Status', 'Level of Education', None, None, None, None, None, None, None, None, None, None, None, 'Do you have children?', None, None, None], column_names_to_labels={'Gender': None, 'Age': None, 'MStatus': None, 'Children#': '# of Children', 'Education': None, 'Ethnicity': None, 'Yeas#': '# of Years at Current Job', 'Location': 'Region', 'MStatus_Rec': 'Marital Status', 'Education_Rec': 'Level of Education', 'Satisfaction': None, 'Burnout': None, 'Turnover': None, 'Colleague': None, 'Supervision': None, 'Salary': None, 'Promotion': None, 'Autonomy': None, 'RoleConflict': None, 'Comfort': None, 'WorkLoad': None, 'AnyChild': 'Do you have children?', 'North': None, 'Center': None, 'South': None}, file_encoding='WINDOWS-1252', file_label=None, number_columns=25, number_rows=218, variable_value_labels={'Gender': {0.0: 'MALE', 1.0: 'FEMALE'}, 'MStatus': {1.0: 'MARRIED', 2.0: 'SINGLE', 3.0: 'DIVORCED'}, 'Education': {1.0: 'BSW/BA', 2.0: 'MSW', 3.0: 'OTHER'}, 'Ethnicity': {0.0: 'JEWS', 1.0: 'ARABS'}, 'Location': {1.0: 'NORTH', 2.0: 'CENTER', 3.0: 'SOUTH'}, 'MStatus_Rec': {0.0: 'Married', 1.0: 'Never Married'}, 'Education_Rec': {0.0: 'Undergraduate', 1.0: 'Graduate'}, 'AnyChild': {0.0: 'No', 1.0: 'Yes'}, 'North': {0.0: 'Others', 1.0: 'North'}, 'Center': {0.0: 'Others', 1.0: 'Center'}, 'South': {0.0: 'Others', 1.0: 'South'}}, value_labels={'labels0': {0.0: 'MALE', 1.0: 'FEMALE'}, 'labels1': {1.0: 'MARRIED', 2.0: 'SINGLE', 3.0: 'DIVORCED'}, 'labels2': {1.0: 'BSW/BA', 2.0: 'MSW', 3.0: 'OTHER'}, 'labels3': {0.0: 'JEWS', 1.0: 'ARABS'}, 'labels4': {1.0: 'NORTH', 2.0: 'CENTER', 3.0: 'SOUTH'}, 'labels5': {0.0: 'Married', 1.0: 'Never Married'}, 'labels6': {0.0: 'Undergraduate', 1.0: 'Graduate'}, 'labels7': {0.0: 'No', 1.0: 'Yes'}, 'labels8': {0.0: 'Others', 1.0: 'North'}, 'labels9': {0.0: 'Others', 1.0: 'Center'}, 'labels10': {0.0: 'Others', 1.0: 'South'}}, variable_to_label={'Gender': 'labels0', 'MStatus': 'labels1', 'Education': 'labels2', 'Ethnicity': 'labels3', 'Location': 'labels4', 'MStatus_Rec': 'labels5', 'Education_Rec': 'labels6', 'AnyChild': 'labels7', 'North': 'labels8', 'Center': 'labels9', 'South': 'labels10'}, notes=[], original_variable_types={'Gender': 'F8.0', 'Age': 'F8.0', 'MStatus': 'F8.0', 'Children#': 'F8.0', 'Education': 'F8.0', 'Ethnicity': 'F8.0', 'Yeas#': 'F8.0', 'Location': 'F8.0', 'MStatus_Rec': 'F8.0', 'Education_Rec': 'F8.0', 'Satisfaction': 'F8.0', 'Burnout': 'F8.0', 'Turnover': 'F8.0', 'Colleague': 'F8.0', 'Supervision': 'F8.0', 'Salary': 'F8.0', 'Promotion': 'F8.0', 'Autonomy': 'F8.0', 'RoleConflict': 'F8.0', 'Comfort': 'F8.0', 'WorkLoad': 'F8.0', 'AnyChild': 'F8.0', 'North': 'F8.0', 'Center': 'F8.0', 'South': 'F8.0'}, original_variable_informats={'Gender': None, 'Age': None, 'MStatus': None, 'Children#': None, 'Education': None, 'Ethnicity': None, 'Yeas#': None, 'Location': None, 'MStatus_Rec': None, 'Education_Rec': None, 'Satisfaction': None, 'Burnout': None, 'Turnover': None, 'Colleague': None, 'Supervision': None, 'Salary': None, 'Promotion': None, 'Autonomy': None, 'RoleConflict': None, 'Comfort': None, 'WorkLoad': None, 'AnyChild': None, 'North': None, 'Center': None, 'South': None}, readstat_variable_types={'Gender': 'double', 'Age': 'double', 'MStatus': 'double', 'Children#': 'double', 'Education': 'double', 'Ethnicity': 'double', 'Yeas#': 'double', 'Location': 'double', 'MStatus_Rec': 'double', 'Education_Rec': 'double', 'Satisfaction': 'double', 'Burnout': 'double', 'Turnover': 'double', 'Colleague': 'double', 'Supervision': 'double', 'Salary': 'double', 'Promotion': 'double', 'Autonomy': 'double', 'RoleConflict': 'double', 'Comfort': 'double', 'WorkLoad': 'double', 'AnyChild': 'double', 'North': 'double', 'Center': 'double', 'South': 'double'}, table_name=None, missing_ranges={}, missing_user_values={}, variable_storage_width={'Gender': 8, 'Age': 8, 'MStatus': 8, 'Children#': 8, 'Education': 8, 'Ethnicity': 8, 'Yeas#': 8, 'Location': 8, 'MStatus_Rec': 8, 'Education_Rec': 8, 'Satisfaction': 8, 'Burnout': 8, 'Turnover': 8, 'Colleague': 8, 'Supervision': 8, 'Salary': 8, 'Promotion': 8, 'Autonomy': 8, 'RoleConflict': 8, 'Comfort': 8, 'WorkLoad': 8, 'AnyChild': 8, 'North': 8, 'Center': 8, 'South': 8}, variable_display_width={'Gender': 6, 'Age': 5, 'MStatus': 6, 'Children#': 8, 'Education': 8, 'Ethnicity': 7, 'Yeas#': 6, 'Location': 8, 'MStatus_Rec': 6, 'Education_Rec': 7, 'Satisfaction': 8, 'Burnout': 6, 'Turnover': 6, 'Colleague': 8, 'Supervision': 8, 'Salary': 6, 'Promotion': 8, 'Autonomy': 8, 'RoleConflict': 8, 'Comfort': 8, 'WorkLoad': 8, 'AnyChild': 8, 'North': 8, 'Center': 8, 'South': 8}, variable_alignment={'Gender': 'unknown', 'Age': 'unknown', 'MStatus': 'unknown', 'Children#': 'unknown', 'Education': 'unknown', 'Ethnicity': 'unknown', 'Yeas#': 'unknown', 'Location': 'unknown', 'MStatus_Rec': 'unknown', 'Education_Rec': 'unknown', 'Satisfaction': 'unknown', 'Burnout': 'unknown', 'Turnover': 'unknown', 'Colleague': 'unknown', 'Supervision': 'unknown', 'Salary': 'unknown', 'Promotion': 'unknown', 'Autonomy': 'unknown', 'RoleConflict': 'unknown', 'Comfort': 'unknown', 'WorkLoad': 'unknown', 'AnyChild': 'unknown', 'North': 'unknown', 'Center': 'unknown', 'South': 'unknown'}, variable_measure={'Gender': 'nominal', 'Age': 'scale', 'MStatus': 'nominal', 'Children#': 'scale', 'Education': 'nominal', 'Ethnicity': 'nominal', 'Yeas#': 'scale', 'Location': 'nominal', 'MStatus_Rec': 'nominal', 'Education_Rec': 'nominal', 'Satisfaction': 'scale', 'Burnout': 'scale', 'Turnover': 'scale', 'Colleague': 'scale', 'Supervision': 'scale', 'Salary': 'scale', 'Promotion': 'scale', 'Autonomy': 'scale', 'RoleConflict': 'scale', 'Comfort': 'scale', 'WorkLoad': 'scale', 'AnyChild': 'nominal', 'North': 'nominal', 'Center': 'nominal', 'South': 'nominal'}, creation_time=datetime.datetime(2010, 2, 26, 13, 16, 52), modification_time=datetime.datetime(2010, 2, 26, 13, 16, 52), mr_sets={})

The metadata_container is exactly what it says, it is a holder for all the information in the data that is not explicitly the numerical data itself. If you scroll along you will see some very useful things, such as the variable_value_labels because Gender = 0 or Gender = 1 is useful for calculations, but not for our human insight. There is also a column_label list because columns are not always named in a way that outsiders can easily decipher. Both of these are important contextual clue about the dataset as a whole.

Can you access the column_labels and variable_value_labels and print them both out?

<details>
<summary><b></b><i>Hint</i></summary>
    Both of these values are attributes of the object we have called meta. How do we access attributes and methods of objects?
</details>

<div class=\"alert alert-success\">
    <details>
    <summary><b></b><i>Click for answer</i></summary>

        print(meta.column_labels)
        print(meta.variable_value_labels)
        
</div>

Next up is editing and writing the edited data to a new file.

You can change df as you would any other pandas dataframe. Filter, drop, conditional changes, individual cell changes, rows or columns replaced with lists are some of the ways you might change the data.

Once the data is changed use the pyreadstat.write_sav() function to save the data. To get more information on the function use "?pyreadstat.write_sav". Try to save as much of the original metadata to the file as you can.

<div class=\"alert alert-success\">
    <details>
    <summary><b></b><i>Click for answer</i></summary>

    #?pyreadstat.write_sav
    # Limiting the age range of the group
    df = df.loc[(df["Age"] >=30) & (df["Age"] <=50)]
    # df # Check that the change took effect
    # Saving the filtered dataset
    pyreadstat.write_sav(
        df, 
        "job_satifaction_30_50.sav", 
        column_labels=meta.column_labels, 
        note = "Respondents in the age range of 30 to 50.", 
        variable_value_labels=meta.variable_value_labels
        )
</details>

### SAS

SAS files are much the same methodology as SPSS files and in fact we use the same package to read and write them. They are also split into the data and the metadata. SAS data is also tabular (tables of data) like excel or a dataframe.

In [24]:
df, meta = pyreadstat.read_sas7bdat("wellbeing.sas7bdat", user_missing=True)
df

,Gender,Age,Race,MaritalStatus,FinancialStatus,PhysicalHealth,LifeSatisfaction,SelfEsteem,Depression,SelfPerception,Weight,Overweight,Race_Rec,ph
0,1.0,25.0,2.0,2.0,3.0,5.0,35.0,37.0,7.0,56.0,2.0,0.0,0.0,50.0
1,1.0,20.0,2.0,1.0,2.0,5.0,34.0,32.0,15.0,55.0,2.0,0.0,0.0,50.0
2,1.0,18.0,2.0,1.0,3.0,4.0,31.0,27.0,16.0,59.0,3.0,1.0,0.0,40.0
3,1.0,21.0,2.0,1.0,3.0,5.0,31.0,31.0,9.0,51.0,2.0,0.0,0.0,50.0
4,1.0,20.0,2.0,1.0,3.0,5.0,28.0,30.0,12.0,49.0,2.0,0.0,0.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,0.0,26.0,1.0,1.0,2.0,3.0,26.0,28.0,28.0,36.0,2.0,0.0,1.0,30.0
178,0.0,27.0,1.0,3.0,2.0,3.0,23.0,28.0,28.0,34.0,4.0,1.0,1.0,30.0
179,0.0,21.0,1.0,1.0,3.0,3.0,35.0,36.0,4.0,32.0,3.0,1.0,1.0,30.0
180,0.0,26.0,1.0,3.0,2.0,2.0,12.0,31.0,12.0,38.0,4.0,1.0,1.0,20.0
181,0.0,21.0,3.0,1.0,3.0,3.0,30.0,35.0,20.0,12.0,2.0,0.0,0.0,30.0

In [ ]:
# The metadata format should look very familiar to the above example.
meta

metadata_container(column_names=['Gender', 'Age', 'Race', 'MaritalStatus', 'FinancialStatus', 'PhysicalHealth', 'LifeSatisfaction', 'SelfEsteem', 'Depression', 'SelfPerception', 'Weight', 'Overweight', 'Race_Rec', 'ph'], column_labels=[None, None, None, None, 'Overall financial status', 'Overall physical health', None, None, None, None, 'Body Mass Index', 'Are you overweight?', None, None], column_names_to_labels={'Gender': None, 'Age': None, 'Race': None, 'MaritalStatus': None, 'FinancialStatus': 'Overall financial status', 'PhysicalHealth': 'Overall physical health', 'LifeSatisfaction': None, 'SelfEsteem': None, 'Depression': None, 'SelfPerception': None, 'Weight': 'Body Mass Index', 'Overweight': 'Are you overweight?', 'Race_Rec': None, 'ph': None}, file_encoding='WINDOWS-1252', file_label='Written by SAS', number_columns=14, number_rows=182, variable_value_labels={}, value_labels={}, variable_to_label={}, notes=[], original_variable_types={'Gender': None, 'Age': None, 'Race': None, 'MaritalStatus': None, 'FinancialStatus': None, 'PhysicalHealth': None, 'LifeSatisfaction': None, 'SelfEsteem': None, 'Depression': None, 'SelfPerception': None, 'Weight': None, 'Overweight': None, 'Race_Rec': None, 'ph': None}, original_variable_informats={'Gender': None, 'Age': None, 'Race': None, 'MaritalStatus': None, 'FinancialStatus': None, 'PhysicalHealth': None, 'LifeSatisfaction': None, 'SelfEsteem': None, 'Depression': None, 'SelfPerception': None, 'Weight': None, 'Overweight': None, 'Race_Rec': None, 'ph': None}, readstat_variable_types={'Gender': 'double', 'Age': 'double', 'Race': 'double', 'MaritalStatus': 'double', 'FinancialStatus': 'double', 'PhysicalHealth': 'double', 'LifeSatisfaction': 'double', 'SelfEsteem': 'double', 'Depression': 'double', 'SelfPerception': 'double', 'Weight': 'double', 'Overweight': 'double', 'Race_Rec': 'double', 'ph': 'double'}, table_name='WELLBEING', missing_ranges={}, missing_user_values={}, variable_storage_width={'Gender': 8, 'Age': 8, 'Race': 8, 'MaritalStatus': 8, 'FinancialStatus': 8, 'PhysicalHealth': 8, 'LifeSatisfaction': 8, 'SelfEsteem': 8, 'Depression': 8, 'SelfPerception': 8, 'Weight': 8, 'Overweight': 8, 'Race_Rec': 8, 'ph': 8}, variable_display_width={'Gender': 0, 'Age': 0, 'Race': 0, 'MaritalStatus': 0, 'FinancialStatus': 0, 'PhysicalHealth': 0, 'LifeSatisfaction': 0, 'SelfEsteem': 0, 'Depression': 0, 'SelfPerception': 0, 'Weight': 0, 'Overweight': 0, 'Race_Rec': 0, 'ph': 0}, variable_alignment={'Gender': 'unknown', 'Age': 'unknown', 'Race': 'unknown', 'MaritalStatus': 'unknown', 'FinancialStatus': 'unknown', 'PhysicalHealth': 'unknown', 'LifeSatisfaction': 'unknown', 'SelfEsteem': 'unknown', 'Depression': 'unknown', 'SelfPerception': 'unknown', 'Weight': 'unknown', 'Overweight': 'unknown', 'Race_Rec': 'unknown', 'ph': 'unknown'}, variable_measure={'Gender': 'unknown', 'Age': 'unknown', 'Race': 'unknown', 'MaritalStatus': 'unknown', 'FinancialStatus': 'unknown', 'PhysicalHealth': 'unknown', 'LifeSatisfaction': 'unknown', 'SelfEsteem': 'unknown', 'Depression': 'unknown', 'SelfPerception': 'unknown', 'Weight': 'unknown', 'Overweight': 'unknown', 'Race_Rec': 'unknown', 'ph': 'unknown'}, creation_time=datetime.datetime(2009, 11, 18, 0, 42, 46), modification_time=datetime.datetime(2009, 11, 18, 0, 42, 46), mr_sets={})

Unfortunately, due to the closed nature of the sas7bdat file type we cannot write to it at this time, we can however write to the SAS file type xpt (Xport). This is done with "pyreadstat.write_xport()". Try making a change to the dataset and exporting it to a ".xpt" file.

<div class=\"alert alert-success\">
    <details>
    <summary><b></b><i>Click for answer</i></summary>

    # Filtering for those with above average Depression scores
    df = df.loc[df["Depression"] > 11.7]
    # Exporting to xpt file
    pyreadstat.write_xport(
        df, 
        "wellbeing_depressed.xpt", 
        column_labels=meta.column_labels, 
        file_label=meta.file_label
        )    
</div>

pyreadstat can also read these files with "pyreadstat.read_xport()", try opening the file you just saved.

<div class=\"alert alert-success\">
    <details>
    <summary><b></b><i>Click for answer</i></summary>

    df, meta = pyreadstat.read_xport("wellbeing_depressed.xpt")
    df
</div>

### STATA

### Excel

Excel, our old pal (or nemesis), has a "suped up csv" format, the xlsx file. You may also occasionally see the old ".xls" files about, but newer ones will always be ".xlsx". 

Thankfully they can be read in and save directly with pandas. Instead of "pd.read_csv()", just change it to "pd.read_excel()".

In [ ]:
#%pip install openpyxl

In [39]:
# %pip install openpyxl
# import pandas as pd
# import openpyxl
country_temp_df = pd.read_excel("Temperatures.xlsx", sheet_name="Countries")

no_s_country_temps = country_temp_df.loc[~country_temp_df["Country"].str.startswith("S")]
no_s_country_temps.to_excel("Temperatures_no_S.xlsx")

<div class=\"alert alert-success\">
    <details>
    <summary><b></b><i>Click for answer</i></summary>
    
    import openpyxl

    country_temp_df = pd.read_excel("Temperatures.xlsx", sheet_name="Countries")
</div>

Saving is just as simple by using "df.to_excel()".

<div class=\"alert alert-success\">
    <details>
    <summary><b></b><i>Click for answer</i></summary>

    no_s_country_temps = country_temp_df.loc[~country_temp_df["Country"].str.startswith("S")]
    no_s_country_temps.to_excel("Temperatures_no_S.xlsx")
</dev>

If you open up the file we just saved with excel, libre office or another open source tool you'll notice an additional column in the data, the index. We can leave out the index column with another argument "index=False" as the default is True. 


One of the useful things about xlsx files is that they can have more than one "sheet". When reading in an excel file we can choose the page we want to read, but updating a sheet is a bit more difficult. You will notice that our output file has only one sheet and it has not retained the name. The default saving of excel files in pandas only works with a single sheet file, let's take a look at how to update existing files to allow for multiple sheets files.

First we create an ExcelWriter object that we feed to the ".to_excel()" method so it knows how we want it to write out the data. "pd.ExcelWriter()" has a few arguments that are important here, the first is the file we are targeting, the "engine" argument we will tell in this case to use "openpyxl" because it has the features we are after. In this example we are appending to our initial output so we set the "mode" as "a", for append. The default mode is "w", for write. The last argument that is interesting for us is the "if_sheet_exists" argument that decides what to do if the sheet you name already exists in the file. In this situation we are updating the dataframe from that sheet and so will "replace" it entirely.

The task here is to open the second sheet in "Temperatures.xlsx" file, filter to keep only the cities with less than 23 temperature and append a sheet called "City" to the output file from the previous step without an index column?


Can you create a variable 'writer' to contain the pd.ExcelWriter object

In [ ]:
writer = pd.ExcelWriter(out_file, engine='openpyxl', mode='a', if_sheet_exists="replace")
print("writer made")
sheet_1_clean.to_excel(writer, sheet_name=sheet_1,index=False)
sheet_2_clean.to_excel(writer, sheet_name=sheet_2,index=False)
print("pandas complete")
writer.close()

<div class=\"alert alert-success\">
    <details>
    <summary><b></b><i>Click for answer</i></summary>

    city_temp_df = pd.read_excel("Temperature.xlsx", sheet_name="Capitals")
    city_temp_df = city_temp_df.loc[city_temp_df["Temperature"] <23]
    
    writer = pd.ExcelWriter("Temperature_no_S.xlsx", engine='openpyxl', mode='a', if_sheet_exists="replace")
    city_temp_df.to_excel(writer, sheet_name="City", index=False)
<div>

### JSON

JSON is a common format to come across the more programming you do. For instance many APIs and web requests to servers will return a ".json" file when successful. Knowing how they are structured and how to use them is therefore an important skill. 

JSON is the first file type in this guide/homework that is not tabular. It's structure is a lot like a Python dictionary. Everything is inside {} and each variable has a ":" to split the name and the values attached to it. It can also have multiple levels, for example:

{
 "House_type": {
    "Bungalow":14,
    "Terrace": 9,
    "Semi-detached": 2,
    "Detached": 101
 },
 "Population": 1036,
 "Complete": True   
}

To work with jsons there are many libraries you can use

### MATLAB

# Categorical Data

A lot of fields (social sciences and humanities in particular) make use of categorical data. For those coming from the R programming language you might already be familiar with [factor types](https://r-statistics.co/R-Factors.html). This is a data type for categorical data that allows for labelling and selecting orders or designating the variable to be unordered.
In Python the equivalent can be done with the [Categoricals](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html) data type in pandas.

# Cleaning

### Conditional Filtering

###

# Plots

# Analyses

https://scikit-learn.org/stable/index.html 
https://realpython.com/python-for-data-analysis/#performing-data-analysis-with-python